import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useMutation } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, BarChart3, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "../../components/ui/Button";
import { Input } from "../../components/ui/Input";
import { Card } from "../../components/ui/Card";
import { authStorage } from "../../lib/auth";
import { getApiErrorMessage } from "../../lib/apiClient";
import { login } from "./auth.api";

export function LoginPage() {
  const navigate = useNavigate();
  const [error, setError] = useState("");
  const mutation = useMutation({ mutationFn: login, onSuccess: (data) => { authStorage.setToken(data.access_token); authStorage.setUser(data.user); navigate(data.user.role === "TEAM_MEMBER" ? "/member/dashboard" : "/manager/dashboard"); }, onError: (err) => setError(getApiErrorMessage(err)) });
  function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const formData = new FormData(event.currentTarget); mutation.mutate({ email: String(formData.get("email")), password: String(formData.get("password")) }); }
  return <div className="grid min-h-screen bg-slate-100 lg:grid-cols-[1.05fr_.95fr]"><div className="relative hidden overflow-hidden bg-slate-950 p-10 text-white lg:block"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(99,102,241,.45),transparent_28rem),radial-gradient(circle_at_80%_10%,rgba(6,182,212,.35),transparent_24rem)]" /><div className="relative flex h-full flex-col justify-between"><div><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10 ring-1 ring-white/15"><Sparkles className="h-5 w-5 text-cyan-200" /></div><div><p className="text-xl font-bold">PulseBoard</p><p className="text-sm text-slate-300">Premium reporting OS</p></div></div><h1 className="mt-20 max-w-xl text-5xl font-bold tracking-tight">A polished command center for weekly team intelligence.</h1><p className="mt-5 max-w-lg text-base leading-7 text-slate-300">Track submissions, blockers, workload, and AI summaries in one modern SaaS workspace.</p></div><div className="grid gap-4 rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur-xl"><div className="flex items-center gap-3"><BarChart3 className="h-5 w-5 text-cyan-200" /><span className="text-sm font-semibold">Live analytics dashboard</span></div><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-200" /><span className="text-sm font-semibold">Role-based workflows</span></div></div></div></div><div className="flex items-center justify-center px-4 py-12"><Card className="w-full max-w-md shadow-panel"><Link to="/" className="mb-5 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-500 transition hover:text-violet-700"><ArrowLeft className="h-4 w-4" />Back to home</Link><div className="mb-6"><p className="text-sm font-semibold text-brand-600">Welcome back</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Sign in to PulseBoard</h1><p className="mt-2 text-sm text-slate-500">Access reports, dashboards, and team insights.</p></div>{error && <div className="mb-5 rounded-2xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700 ring-1 ring-red-100">{error}</div>}<form onSubmit={handleSubmit} className="space-y-4"><Input label="Email" name="email" type="email" required /><Input label="Password" name="password" type="password" required /><Button className="w-full" isLoading={mutation.isPending}>Sign in <ArrowRight className="h-4 w-4" /></Button></form><p className="mt-6 text-center text-sm text-slate-500">No account? <Link className="font-semibold text-brand-600 hover:text-brand-700" to="/register">Create one</Link></p></Card></div></div>;
}
